#!/bin/bash
echo "Helping..."
echo ""
echo ""

echo "Claude Code PM - Project Management System"
echo "============================================="
echo ""
echo "Workflows"
echo ""
echo "  Simple (single epic, all-in-one):"
echo "    /ccpm:initiative-new <name>"
echo "    /ccpm:initiative-go <name>           - Parse, decompose, start agents"
echo "    /ccpm:initiative-merge <name>        - Merge everything to main"
echo ""
echo "  Step-by-step (single epic, full control):"
echo "    /ccpm:initiative-new <name>"
echo "    /ccpm:initiative-parse <name>        - Convert to epic"
echo "    /ccpm:epic-decompose <name>          - Break into tasks"
echo "    /ccpm:epic-start <name>              - Launch agents"
echo "    /ccpm:initiative-merge <name>        - Merge everything to main"
echo ""
echo "  Multi-epic (large initiatives, up to 10 epics):"
echo "    /ccpm:initiative-new <name>"
echo "    /ccpm:initiative-decompose <name>    - Break into multiple epics"
echo "    For each epic:"
echo "      /ccpm:epic-decompose <epic>        - Break epic into tasks"
echo "      /ccpm:epic-start <epic>            - Launch agents"
echo "    /ccpm:initiative-merge <name>        - Merge all epics to main"
echo ""
echo "Initiative Commands"
echo "  /ccpm:initiative-new <name>       - Launch brainstorming for new initiative"
echo "  /ccpm:initiative-parse <name>     - Convert initiative to single epic"
echo "  /ccpm:initiative-decompose <name> - Break initiative into multiple epics"
echo "  /ccpm:initiative-go <name>        - Parse, decompose, and start (all-in-one)"
echo "  /ccpm:initiative-merge <name>     - Merge initiative branch to main"
echo "  /ccpm:initiative-list             - List all initiatives"
echo "  /ccpm:initiative-edit <name>      - Edit existing initiative"
echo "  /ccpm:initiative-status           - Show initiative implementation status"
echo ""
echo "Epic Commands"
echo "  /ccpm:epic-decompose <name> - Break epic into task files"
echo "  /ccpm:epic-sync <name>      - Push epic and tasks to GitHub"
echo "  /ccpm:epic-oneshot <name>   - Decompose and sync in one command"
echo "  /ccpm:epic-list             - List all epics"
echo "  /ccpm:epic-show <name>      - Display epic and its tasks"
echo "  /ccpm:epic-status [name]    - Show epic progress"
echo "  /ccpm:epic-close <name>     - Mark epic as complete"
echo "  /ccpm:epic-edit <name>      - Edit epic details"
echo "  /ccpm:epic-refresh <name>   - Update epic progress from tasks"
echo "  /ccpm:epic-start <name>     - Launch parallel agent execution"
echo "  /ccpm:epic-merge <name>     - Merge epic to initiative branch"
echo ""
echo "Issue Commands"
echo "  /ccpm:issue-show <num>      - Display issue and sub-issues"
echo "  /ccpm:issue-status <num>    - Check issue status"
echo "  /ccpm:issue-start <num>     - Begin work with specialized agent"
echo "  /ccpm:issue-sync <num>      - Push updates to GitHub"
echo "  /ccpm:issue-close <num>     - Mark issue as complete"
echo "  /ccpm:issue-reopen <num>    - Reopen closed issue"
echo "  /ccpm:issue-edit <num>      - Edit issue details"
echo "  /ccpm:issue-analyze <num>   - Analyze for parallel work streams"
echo ""
echo "Workflow Commands"
echo "  /ccpm:next               - Show next priority tasks"
echo "  /ccpm:status             - Overall project dashboard"
echo "  /ccpm:standup            - Daily standup report"
echo "  /ccpm:blocked            - Show blocked tasks"
echo "  /ccpm:in-progress        - List work in progress"
echo ""
echo "Sync Commands"
echo "  /ccpm:sync               - Full bidirectional sync with GitHub"
echo "  /ccpm:import <issue>     - Import existing GitHub issues"
echo ""
echo "Maintenance Commands"
echo "  /ccpm:validate           - Check system integrity"
echo "  /ccpm:clean              - Archive completed work"
echo "  /ccpm:search <query>     - Search across all content"
echo ""
echo "Setup Commands"
echo "  /ccpm:init               - Install dependencies and configure GitHub"
echo "  /ccpm:help               - Show this help message"
echo ""
echo "Tips"
echo "  - Use /ccpm:next to find available work"
echo "  - Run /ccpm:status for quick overview"
echo "  - Simple: initiative-new -> initiative-go -> initiative-merge"
echo "  - Step-by-step: initiative-new -> initiative-parse -> epic-decompose -> epic-start -> initiative-merge"
echo "  - Multi-epic: initiative-new -> initiative-decompose -> (epic-decompose + epic-start) x N -> initiative-merge"
echo "  - View README.md for complete documentation"

exit 0
