#!/bin/bash
echo "Helping..."
echo ""
echo ""

echo "Claude Code PM - Project Management System"
echo "============================================="
echo ""
echo "Quick Start Workflow"
echo "  1. /ccpm:initiative-new <name>        - Create a new Initiative"
echo "  2. /ccpm:initiative-parse <name>      - Convert Initiative to epic"
echo "  3. /ccpm:epic-decompose <name> - Break into tasks"
echo "  4. /ccpm:epic-sync <name>      - Push to GitHub"
echo "  5. /ccpm:epic-start <name>     - Start parallel execution"
echo ""
echo "Initiative Commands"
echo "  /ccpm:initiative-new <name>     - Launch brainstorming for new product requirement"
echo "  /ccpm:initiative-parse <name>   - Convert Initiative to implementation epic"
echo "  /ccpm:initiative-list           - List all Initiatives"
echo "  /ccpm:initiative-edit <name>    - Edit existing Initiative"
echo "  /ccpm:initiative-status         - Show Initiative implementation status"
echo ""
echo "Epic Commands"
echo "  /ccpm:epic-decompose <name> - Break epic into task files"
echo "  /ccpm:epic-sync <name>      - Push epic and tasks to GitHub"
echo "  /ccpm:epic-oneshot <name>   - Decompose and sync in one command"
echo "  /ccpm:epic-list             - List all epics"
echo "  /ccpm:epic-show <name>      - Display epic and its tasks"
echo "  /ccpm:epic-status [name]    - Show epic progress"
echo "  /ccpm:epic-close <name>     - Mark epic as complete"
echo "  /ccpm:epic-edit <name>      - Edit epic details"
echo "  /ccpm:epic-refresh <name>   - Update epic progress from tasks"
echo "  /ccpm:epic-start <name>     - Launch parallel agent execution"
echo ""
echo "Issue Commands"
echo "  /ccpm:issue-show <num>      - Display issue and sub-issues"
echo "  /ccpm:issue-status <num>    - Check issue status"
echo "  /ccpm:issue-start <num>     - Begin work with specialized agent"
echo "  /ccpm:issue-sync <num>      - Push updates to GitHub"
echo "  /ccpm:issue-close <num>     - Mark issue as complete"
echo "  /ccpm:issue-reopen <num>    - Reopen closed issue"
echo "  /ccpm:issue-edit <num>      - Edit issue details"
echo "  /ccpm:issue-analyze <num>   - Analyze for parallel work streams"
echo ""
echo "Workflow Commands"
echo "  /ccpm:next               - Show next priority tasks"
echo "  /ccpm:status             - Overall project dashboard"
echo "  /ccpm:standup            - Daily standup report"
echo "  /ccpm:blocked            - Show blocked tasks"
echo "  /ccpm:in-progress        - List work in progress"
echo ""
echo "Sync Commands"
echo "  /ccpm:sync               - Full bidirectional sync with GitHub"
echo "  /ccpm:import <issue>     - Import existing GitHub issues"
echo ""
echo "Maintenance Commands"
echo "  /ccpm:validate           - Check system integrity"
echo "  /ccpm:clean              - Archive completed work"
echo "  /ccpm:search <query>     - Search across all content"
echo ""
echo "Setup Commands"
echo "  /ccpm:init               - Install dependencies and configure GitHub"
echo "  /ccpm:help               - Show this help message"
echo ""
echo "Tips"
echo "  - Use /ccpm:next to find available work"
echo "  - Run /ccpm:status for quick overview"
echo "  - Epic workflow: initiative-new -> initiative-parse -> epic-decompose -> epic-sync"
echo "  - View README.md for complete documentation"

exit 0
